version: "3.6"
services:
  ganache:
    image: ganache
    container_name: ganache
    ports:
      - 8545:8545
    networks:
      - web
  truffle:
    image: truffle
    container_name: truffle
    stdin_open: true
    tty: true
    depends_on:
      - ganache
    networks:
      - web
  hardhat:
    image: hardhat
    container_name: hardhat
    stdin_open: true
    tty: true
    depends_on:
      - ganache
    networks:
      - web
networks:
  web:
    name: web
    driver: bridge