version: "3.6"
services:
  ganache:
    image: olelarsen/ganache
    container_name: ganache
    volumes:
      - ./source/ganache:/ganache
    ports:
      - 8545:8545
    networks:
      - web
  truffle:
    image: olelarsen/truffle
    container_name: truffle
    stdin_open: true
    tty: true
    depends_on:
      - ganache
    volumes:
      - ./source/truffle:/truffle
    ports:
      - 3000:3000
    networks:
      - web
  hardhat:
    image: olelarsen/hardhat
    container_name: hardhat
    stdin_open: true
    tty: true
    depends_on:
      - ganache
    volumes:
      - ./source/hardhat:/hardhat
    networks:
      - web
networks:
  web:
    name: web
    driver: bridge